export enum RoutePath {
  Home = '/',
  Login = '/login',
  Nft = '/nft',
  Staking = '/staking',
  Explore = '/explore',
  History = '/history',
  Create = '/create',

  //phrase
  EnterSeedPhrase = '/popup/enter-seed',
  CreatePassword = '/popup/create-password',
  LaunchAdena = '/popup/launch-adena',
  YourSeedPhrase = '/popup/your-seed-phrase',

  //wallet
  Wallet = '/wallet',
  WalletSearch = '/wallet/search',
  TransactionDetail = '/wallet/transaction-detail',
  Deposit = '/wallet/deposit',
  Send = '/wallet/send',
  GeneralSend = '/wallet/general-send',
  SendConfirm = '/wallet/send-confirm',
  TokenDetails = '/wallet/token-details',
  ApproveLogin = '/approve/wallet/login',
  ApproveTransaction = '/approve/wallet/transaction',
  ApproveEstablish = '/approve/wallet/establish',
  ImportAccount = '/wallet/import-account',
  AddAccount = '/wallet/add-account',

  // settings
  Setting = '/settings',
  SettingChangePassword = '/settings/change-password',
  SettingExportAccount = '/settings/export-account',
  SettingSeedPhrase = '/settings/seed-phrase',
  ViewPrivateKey = '/settings/view-private-key',
  ViewSeedPhrase = '/settings/view-seed-phrase',
  ConnectedApps = '/settings/connected-apps',
  ChangeNetwork = '/settings/change-network',
  AddressBook = '/settings/address-book',
  AddAddress = '/settings/add-address',
  ApproveHardwareWalletInit = '/approve/settings/hardware-wallet',
  ApproveHardwareWalletConnect = '/approve/settings/hardware-wallet/connect',
  ApproveHardwareWalletSelectAccount = '/approve/settings/hardware-wallet/select-account',
  ApproveHardwareWalletFinish = '/approve/settings/hardware-wallet/finish',
}
