name: Setup
description: Set up project environment and test environment.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@v3
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: |
        yarn install -g nx
        yarn install
      shell: bash
