nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: loose

enableTelemetry: false

yarnPath: .yarn/releases/yarn-3.4.1.cjs
enableScripts: false

packageExtensions:
  # This is a workaround for the following issue:
  '@walletconnect/socket-transport@*':
    dependencies:
      ws: '8.18.0'
  '@walletconnect/jsonrpc-ws-connection@*':
    dependencies:
      ws: '8.18.0'
