// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: gno/vm.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import Long from 'long';
import { Any } from '../google/protobuf/any';

export const protobufPackage = 'gno.vm';

/**
 * MsgCall is the method invocation tx message,
 * denoted as "m_call"
 */
export interface MsgCall {
  /** the bech32 address of the caller */
  caller: string;
  /** the amount of funds to be deposited to the package, if any ("<amount><denomination>") */
  send: string;
  /** the gno package path */
  pkg_path: string;
  /** the function name being invoked */
  func: string;
  /** the function arguments */
  args: string[] | null;
  /** the amount of funds to lock for the storage, if any ("<amount><denomination>") */
  max_deposit: string;
}

/**
 * MsgAddPackage is the package deployment tx message,
 * denoted as "m_addpkg"
 */
export interface MsgAddPackage {
  /** the package deployer */
  creator: string;
  /** the package being deployed */
  package?: MemPackage | undefined;
  /** the amount of funds to be deposited at deployment, if any ("<amount><denomination>") */
  send: string;
  /** the amount of funds to put down for the storage fee, if any ("<amount><denomination>") */
  max_deposit: string;
}

/**
 * MsgRun is the execute arbitrary Gno code tx message,
 * denoted as "m_run"
 */
export interface MsgRun {
  /** the bech32 address of the caller */
  caller: string;
  /** the amount of funds to be deposited to the package, if any ("<amount><denomination>") */
  send: string;
  /** the package being executed */
  package?: MemPackage | undefined;
  /** the amount of funds to put down for the storage fee, if any ("<amount><denomination>") */
  max_deposit: string;
}

/**
 * MemPackage is the metadata information tied to
 * package / realm deployment
 */
export interface MemPackage {
  /** the name of the package */
  name: string;
  /** the gno path of the package */
  path: string;
  /** the associated package gno source */
  files: MemFile[];
  /** the (user defined) package type */
  type?: Any | undefined;
  /** the (user defined) extra information */
  info?: Any | undefined;
}

/**
 * MemFile is the metadata information tied to
 * a single gno package / realm file
 */
export interface MemFile {
  /** the name of the source gno file */
  name: string;
  /** the content of the source gno file */
  body: string;
}

function createBaseMsgCall(): MsgCall {
  return {
    caller: '',
    send: '',
    pkg_path: '',
    func: '',
    args: null,
    max_deposit: '',
  };
}

export const MsgCall: MessageFns<MsgCall> = {
  encode(message: MsgCall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.caller !== '') {
      writer.uint32(10).string(message.caller);
    }
    if (message.send !== '') {
      writer.uint32(18).string(message.send);
    }
    if (message.max_deposit !== '') {
      writer.uint32(26).string(message.max_deposit);
    }
    if (message.pkg_path !== '') {
      writer.uint32(34).string(message.pkg_path);
    }
    if (message.func !== '') {
      writer.uint32(42).string(message.func);
    }
    if (message.args) {
      for (const v of message.args) {
        writer.uint32(50).string(v!);
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.caller = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.send = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.max_deposit = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.func = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          if (!message.args) {
            message.args = [];
          }

          message.args.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCall {
    return {
      caller: isSet(object.caller) ? globalThis.String(object.caller) : '',
      send: isSet(object.send) ? globalThis.String(object.send) : '',
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
      func: isSet(object.func) ? globalThis.String(object.func) : '',
      args: globalThis.Array.isArray(object?.args)
        ? object.args.map((e: any) => globalThis.String(e))
        : null,
      max_deposit: isSet(object.max_deposit) ? globalThis.String(object.max_deposit) : '',
    };
  },

  toJSON(message: MsgCall): unknown {
    const obj: any = {};
    if (message.caller !== undefined) {
      obj.caller = message.caller;
    }
    if (message.send !== undefined) {
      obj.send = message.send;
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    if (message.func !== undefined) {
      obj.func = message.func;
    }
    if (message.args?.length) {
      obj.args = message.args;
    } else {
      obj.args = null;
    }
    if (message.max_deposit !== undefined) {
      obj.max_deposit = message.max_deposit;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCall>, I>>(base?: I): MsgCall {
    return MsgCall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCall>, I>>(object: I): MsgCall {
    const message = createBaseMsgCall();
    message.caller = object.caller ?? '';
    message.send = object.send ?? '';
    message.pkg_path = object.pkg_path ?? '';
    message.func = object.func ?? '';
    message.args = object.args?.map((e) => e) || [];
    message.max_deposit = object.max_deposit ?? '';
    return message;
  },
};

function createBaseMsgAddPackage(): MsgAddPackage {
  return { creator: '', package: undefined, send: '', max_deposit: '' };
}

export const MsgAddPackage: MessageFns<MsgAddPackage> = {
  encode(message: MsgAddPackage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== '') {
      writer.uint32(10).string(message.creator);
    }
    if (message.package !== undefined) {
      MemPackage.encode(message.package, writer.uint32(18).fork()).join();
    }
    if (message.send !== '') {
      writer.uint32(26).string(message.send);
    }
    if (message.max_deposit !== '') {
      writer.uint32(34).string(message.max_deposit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddPackage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddPackage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.package = MemPackage.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.send = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.max_deposit = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddPackage {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : '',
      package: isSet(object.package) ? MemPackage.fromJSON(object.package) : undefined,
      send: isSet(object.send) ? globalThis.String(object.send) : '',
      max_deposit: isSet(object.max_deposit) ? globalThis.String(object.max_deposit) : '',
    };
  },

  toJSON(message: MsgAddPackage): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    if (message.package !== undefined) {
      obj.package = MemPackage.toJSON(message.package);
    }
    if (message.send !== undefined) {
      obj.send = message.send;
    }
    if (message.max_deposit !== undefined) {
      obj.max_deposit = message.max_deposit;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddPackage>, I>>(base?: I): MsgAddPackage {
    return MsgAddPackage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddPackage>, I>>(object: I): MsgAddPackage {
    const message = createBaseMsgAddPackage();
    message.creator = object.creator ?? '';
    message.package =
      object.package !== undefined && object.package !== null
        ? MemPackage.fromPartial(object.package)
        : undefined;
    message.send = object.send ?? '';
    message.max_deposit = object.max_deposit ?? '';
    return message;
  },
};

function createBaseMsgRun(): MsgRun {
  return { caller: '', send: '', package: undefined, max_deposit: '' };
}

export const MsgRun: MessageFns<MsgRun> = {
  encode(message: MsgRun, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.caller !== '') {
      writer.uint32(10).string(message.caller);
    }
    if (message.send !== '') {
      writer.uint32(18).string(message.send);
    }
    if (message.max_deposit !== '') {
      writer.uint32(26).string(message.max_deposit);
    }
    if (message.package !== undefined) {
      MemPackage.encode(message.package, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRun {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRun();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.caller = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.send = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.max_deposit = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.package = MemPackage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRun {
    return {
      caller: isSet(object.caller) ? globalThis.String(object.caller) : '',
      send: isSet(object.send) ? globalThis.String(object.send) : '',
      package: isSet(object.package) ? MemPackage.fromJSON(object.package) : undefined,
      max_deposit: isSet(object.max_deposit) ? globalThis.String(object.max_deposit) : '',
    };
  },

  toJSON(message: MsgRun): unknown {
    const obj: any = {};
    if (message.caller !== undefined) {
      obj.caller = message.caller;
    }
    if (message.send !== undefined) {
      obj.send = message.send;
    }
    if (message.package !== undefined) {
      obj.package = MemPackage.toJSON(message.package);
    }
    if (message.max_deposit !== undefined) {
      obj.max_deposit = message.max_deposit;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRun>, I>>(base?: I): MsgRun {
    return MsgRun.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRun>, I>>(object: I): MsgRun {
    const message = createBaseMsgRun();
    message.caller = object.caller ?? '';
    message.send = object.send ?? '';
    message.package =
      object.package !== undefined && object.package !== null
        ? MemPackage.fromPartial(object.package)
        : undefined;
    message.max_deposit = object.max_deposit ?? '';
    return message;
  },
};

function createBaseMemPackage(): MemPackage {
  return { name: '', path: '', files: [], type: undefined, info: undefined };
}

export const MemPackage: MessageFns<MemPackage> = {
  encode(message: MemPackage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.path !== '') {
      writer.uint32(18).string(message.path);
    }
    for (const v of message.files) {
      MemFile.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.type !== undefined) {
      Any.encode(message.type, writer.uint32(34).fork()).join();
    }
    if (message.info !== undefined) {
      Any.encode(message.info, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemPackage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemPackage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.files.push(MemFile.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.type = Any.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.info = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemPackage {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      path: isSet(object.path) ? globalThis.String(object.path) : '',
      files: globalThis.Array.isArray(object?.files)
        ? object.files.map((e: any) => MemFile.fromJSON(e))
        : [],
      type: isSet(object.type) ? Any.fromJSON(object.type) : undefined,
      info: isSet(object.info) ? Any.fromJSON(object.info) : undefined,
    };
  },

  toJSON(message: MemPackage): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.path !== undefined) {
      obj.path = message.path;
    }
    if (message.files?.length) {
      obj.files = message.files.map((e) => MemFile.toJSON(e));
    }
    if (message.type !== undefined) {
      obj.type = Any.toJSON(message.type);
    }
    if (message.info !== undefined) {
      obj.info = Any.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemPackage>, I>>(base?: I): MemPackage {
    return MemPackage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemPackage>, I>>(object: I): MemPackage {
    const message = createBaseMemPackage();
    message.name = object.name ?? '';
    message.path = object.path ?? '';
    message.files = object.files?.map((e) => MemFile.fromPartial(e)) || [];
    message.type =
      object.type !== undefined && object.type !== null ? Any.fromPartial(object.type) : undefined;
    message.info =
      object.info !== undefined && object.info !== null ? Any.fromPartial(object.info) : undefined;
    return message;
  },
};

function createBaseMemFile(): MemFile {
  return { name: '', body: '' };
}

export const MemFile: MessageFns<MemFile> = {
  encode(message: MemFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.body !== '') {
      writer.uint32(18).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemFile {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      body: isSet(object.body) ? globalThis.String(object.body) : '',
    };
  },

  toJSON(message: MemFile): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.body !== undefined) {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemFile>, I>>(base?: I): MemFile {
    return MemFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemFile>, I>>(object: I): MemFile {
    const message = createBaseMemFile();
    message.name = object.name ?? '';
    message.body = object.body ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;

  decode(input: BinaryReader | Uint8Array, length?: number): T;

  fromJSON(object: any): T;

  toJSON(message: T): unknown;

  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;

  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
