import { ContractMessage } from '@inject/types';
import {
  MSG_CREATE_SESSION_ENDPOINT,
  MSG_REVOKE_ALL_SESSIONS_ENDPOINT,
  MSG_REVOKE_SESSION_ENDPOINT,
  RawTxMessageType,
} from 'adena-module';

type TransactionMessageInput = {
  type: string;
  value: unknown;
};

type TransactionDocumentMessageInput = {
  type: string;
  value: Record<string, unknown>;
};

type NullableContractMessage = ContractMessage | null;

export function mappedTransactionMessages(messages: unknown[]): ContractMessage[] {
  return messages
    .map<NullableContractMessage>((message) => {
      if (!isTransactionMessageInput(message)) {
        return null;
      }

      switch (message.type) {
        case '/bank.MsgSend':
          return {
            type: '/bank.MsgSend',
            value: message.value as ContractMessage['value'],
          };
        case '/vm.m_call':
          return {
            type: '/vm.m_call',
            value: message.value as ContractMessage['value'],
          };
        case '/vm.m_addpkg':
          return {
            type: '/vm.m_addpkg',
            value: message.value as ContractMessage['value'],
          };
        case '/vm.m_run':
          return {
            type: '/vm.m_run',
            value: message.value as ContractMessage['value'],
          };
        case MSG_CREATE_SESSION_ENDPOINT:
        case MSG_REVOKE_SESSION_ENDPOINT:
        case MSG_REVOKE_ALL_SESSIONS_ENDPOINT:
          return {
            type: message.type as ContractMessage['type'],
            value: message.value as ContractMessage['value'],
          };
      }
      return null;
    })
    .filter(isContractMessage);
}

/**
 * Maps the messages in the Transaction Document.
 * Since caller information does not exist in messages generated by tx link,
 * it is set to the current address information received as a parameter.
 *
 * When `overwrite` is true the supplied address replaces any existing
 * from_address/caller/creator on the message. This is required for SessionAccount
 * documents where the signer is the session key but `from_address`/`caller`
 * must point to the master account.
 *
 * @param messages
 * @param currentAddress
 * @param overwrite force the supplied address even if the message already had one
 * @returns
 */
export function mappedDocumentMessagesWithCaller(
  messages: unknown[],
  currentAddress: string,
  overwrite = false,
): ContractMessage[] {
  if (!messages) {
    return [];
  }

  const pick = (existing: string | undefined): string =>
    overwrite ? currentAddress : existing || currentAddress;

  // Unmappable messages must NOT be silently dropped: this output becomes the
  // signed document, so dropping a message the dApp requested would sign a
  // different (smaller) transaction than intended — a signing-integrity bug.
  // Unsupported types (e.g. /bank.MsgMultiSend, which has no proto encoder)
  // therefore fail closed here.
  return messages.map<ContractMessage>((message, index) => {
    if (!isTransactionDocumentMessageInput(message)) {
      throw new Error(`Unsupported transaction message shape at index ${index}`);
    }

    const type = message.type;
    switch (type) {
      case '/bank.MsgSend':
        return {
          type: '/bank.MsgSend',
          value: {
            ...message.value,
            from_address: pick(toOptionalString(message.value.from_address)),
          } as ContractMessage['value'],
        };
      case '/vm.m_call':
        return {
          type: '/vm.m_call',
          value: {
            ...message.value,
            caller: pick(toOptionalString(message.value.caller)),
          } as ContractMessage['value'],
        };
      case '/vm.m_addpkg':
        return {
          type: '/vm.m_addpkg',
          value: {
            ...message.value,
            creator: pick(toOptionalString(message.value.creator)),
          } as ContractMessage['value'],
        };
      case '/vm.m_run':
        return {
          type: '/vm.m_run',
          value: {
            ...message.value,
            caller: pick(toOptionalString(message.value.caller)),
          } as ContractMessage['value'],
        };
      // Session admin messages all carry `creator` (master address).
      // SessionAccount can never sign these. Issuance/revocation is
      // master-only, so overwrite=true would only ever clobber with
      // the same master address. Keep the same pick() shape for
      // consistency with the spend/call branches.
      case MSG_CREATE_SESSION_ENDPOINT:
      case MSG_REVOKE_SESSION_ENDPOINT:
      case MSG_REVOKE_ALL_SESSIONS_ENDPOINT:
        return {
          type: type as ContractMessage['type'],
          value: {
            ...message.value,
            creator: pick(toOptionalString(message.value.creator)),
          } as ContractMessage['value'],
        };
      default:
        throw new Error(`Unsupported transaction message type "${type}"`);
    }
  });
}

export function mappedRawTxMessages(messages: RawTxMessageType[]): ContractMessage[] {
  if (!messages) {
    return [];
  }

  return messages
    .map<NullableContractMessage>((message) => {
      const type = message['@type'];
      switch (type) {
        case '/bank.MsgSend':
          return {
            type: '/bank.MsgSend',
            value: message as ContractMessage['value'],
          };
        case '/vm.m_call':
          return {
            type: '/vm.m_call',
            value: message as ContractMessage['value'],
          };
        case '/vm.m_addpkg':
          return {
            type: '/vm.m_addpkg',
            value: message as ContractMessage['value'],
          };
        case '/vm.m_run':
          return {
            type: '/vm.m_run',
            value: message as ContractMessage['value'],
          };
        case MSG_CREATE_SESSION_ENDPOINT:
        case MSG_REVOKE_SESSION_ENDPOINT:
        case MSG_REVOKE_ALL_SESSIONS_ENDPOINT:
          return {
            type: type as ContractMessage['type'],
            value: message as ContractMessage['value'],
          };
      }
      return null;
    })
    .filter(isContractMessage);
}

function isTransactionMessageInput(value: unknown): value is TransactionMessageInput {
  return isRecord(value) && typeof value.type === 'string' && 'value' in value;
}

function isTransactionDocumentMessageInput(
  value: unknown,
): value is TransactionDocumentMessageInput {
  return isTransactionMessageInput(value) && isRecord(value.value);
}

function isContractMessage(message: NullableContractMessage): message is ContractMessage {
  return message !== null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function toOptionalString(value: unknown): string | undefined {
  return typeof value === 'string' ? value : undefined;
}
