export { default as IconWallet } from './icon-wallet';
export { default as IconGallery } from './icon-gallery';
export { default as IconSearch } from './icon-search';
export { default as IconClock } from './icon-clock';
export { default as IconSetting } from './icon-setting';
export * from './icon-address-book';
export { default as IconCancel } from './icon-cancel';
export { default as IconArrowV2 } from './icon-arrow-v2';
export { default as IconWebLink } from './icon-weblink';
export { default as IconHiddenEye } from './icon-hidden-eye';
export { default as IconConnectLoading } from './icon-connect-loading';
export { default as IconConnectFailed } from './icon-connect-failed';
export { default as IconTokenAdded } from './icon-token-added';
